name: novelive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  badges: ^3.1.2
  flutter_rating_bar: ^4.0.1
  clippy_flutter: ^2.0.0-nullsafety.1
  curved_navigation_bar: ^1.0.6
  cupertino_icons: ^1.0.0
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets : 
  - images/
  - images/isekai/1.jpg
  - images/isekai/2.jpg
  - images/isekai/3.jpg
  - images/isekai/4.jpg
  - images/isekai/5.jpg